# Generated by Django 2.1.2 on 2018-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('interested_in', models.CharField(choices=[('Blogger', 'blogger'), ('Youtuber', 'youtuber'), ('Local Business', 'local_business'), ('Other', 'other')], default='Blogger', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interested Person',
                'verbose_name_plural': 'Interested People',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
