# Generated by Django 2.1.2 on 2018-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_clientele'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('InReview', 'inreview'), ('Error', 'error'), ('Working', 'working'), ('Completed', 'completed'), ('Rejected', 'rejected')], default='InReview', max_length=20),
        ),
    ]
