# Generated by Django 2.1.2 on 2018-10-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181015_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='client',
            new_name='user',
        ),
    ]
