# Generated by Django 2.1.2 on 2018-10-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181016_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.clientele'),
        ),
    ]
